const Books = [
	"Critical Mass",
	"The Psychology of Money",
	"A Ruse of Shadows",
	"Love, Off the Record",
	"Psychedelic Outlaws",
	"The Occasional Human Sacrifice",
	"Of Jade and Dragons",
	"Fate of the Sun King",
	"Shadow & Storms",
	"Sound the Gong",
	"Laut Bercerita",
	"Hujan",
	"The Architecture of Love",
	"2,578.0 km",
	"Alster Lake",
	"Turning Page",
	"Malioboro at Midnight",
	"Lotus in the Mud",
	"Children of Anguish and Anarchy",
	"The Wicked King",
	"Swallowed Star",
	"Perfect World",
]
